use super::*;

fn save_image(data: &NSData, dir: &Path) -> Option<ClipKind> {
    let bitmap = NSBitmapImageRep::imageRepWithData(data)?;
    let (width, height) = (bitmap.pixelsWide(), bitmap.pixelsHigh());
    // SAFETY: an empty property dictionary is valid for PNG output.
    let png = unsafe {
        bitmap.representationUsingType_properties(NSBitmapImageFileType::PNG, &NSDictionary::new())
    }?;
    std::fs::create_dir_all(dir).ok()?;
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_nanos();
    let path = dir.join(format!("{nanos}.png"));
    std::fs::write(&path, png.to_vec()).ok()?;
    Some(ClipKind::Image {
        path,
        width: width.max(0) as u32,
        height: height.max(0) as u32,
    })
}

pub(super) fn pasteboard_change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

pub(super) fn read_pasteboard(image_dir: &Path) -> Option<Copied> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let types: Vec<String> = pasteboard
        .types()?
        .iter()
        .map(|kind| kind.to_string())
        .collect();
    // Password managers mark secrets; nspasteboard.org documents these.
    const PRIVATE: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ];
    if types.iter().any(|kind| PRIVATE.contains(&kind.as_str())) {
        return None;
    }

    // SAFETY: AppKit's pasteboard type constants are always initialized.
    let (file_url, string, png, tiff) = unsafe {
        (
            NSPasteboardTypeFileURL,
            NSPasteboardTypeString,
            NSPasteboardTypePNG,
            NSPasteboardTypeTIFF,
        )
    };
    let has = |kind: &NSString| types.iter().any(|t| *t == kind.to_string());

    let kind = if has(file_url) {
        let url = pasteboard.stringForType(file_url)?;
        let path = NSURL::URLWithString(&url)?.path()?.to_string();
        ClipKind::File { path: path.into() }
    } else if let Some(text) = pasteboard
        .stringForType(string)
        .filter(|text| text.length() > 0)
    {
        ClipKind::from_text(text.to_string())
    } else if has(png) || has(tiff) {
        let data = pasteboard
            .dataForType(png)
            .or_else(|| pasteboard.dataForType(tiff))?;
        save_image(&data, image_dir)?
    } else {
        return None;
    };

    let source = NSWorkspace::sharedWorkspace()
        .frontmostApplication()
        .and_then(|app| app.localizedName())
        .map(|name| name.to_string());
    Some(Copied { kind, source })
}

pub(super) fn write_pasteboard(kind: &ClipKind) {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    // SAFETY: AppKit's pasteboard type constants are always initialized.
    let (file_url, string, png) = unsafe {
        (
            NSPasteboardTypeFileURL,
            NSPasteboardTypeString,
            NSPasteboardTypePNG,
        )
    };
    match kind {
        ClipKind::Text { text } => {
            pasteboard.setString_forType(&NSString::from_str(text), string);
        }
        ClipKind::Link { url } => {
            pasteboard.setString_forType(&NSString::from_str(url), string);
        }
        ClipKind::Image { path, .. } => {
            if let Ok(bytes) = std::fs::read(path) {
                pasteboard.setData_forType(Some(&NSData::from_vec(bytes)), png);
            }
        }
        ClipKind::File { path } => {
            let url = NSURL::fileURLWithPath(&NSString::from_str(&path.to_string_lossy()));
            if let Some(url) = url.absoluteString() {
                pasteboard.setString_forType(&url, file_url);
            }
        }
    }
}
