// Watches the macOS pasteboard and prints one JSON line per copy, so the
// plugin needs no native code. Run with:
//   osascript -l JavaScript pasteboard.js <image folder>
ObjC.import("AppKit");

// Password managers mark secrets; nspasteboard.org documents these.
const PRIVATE = [
  "org.nspasteboard.ConcealedType",
  "org.nspasteboard.TransientType",
  "org.nspasteboard.AutoGeneratedType",
  "com.agilebits.onepassword",
];
const PNG = 4; // NSBitmapImageFileTypePNG

function emit(value) {
  const line = $.NSString.alloc.initWithUTF8String(JSON.stringify(value) + "\n");
  $.NSFileHandle.fileHandleWithStandardOutput.writeData(
    line.dataUsingEncoding($.NSUTF8StringEncoding),
  );
}

function read(pasteboard, images) {
  const types = ObjC.deepUnwrap(pasteboard.types) || [];
  if (types.some((type) => PRIVATE.includes(type))) return null;
  const app = $.NSWorkspace.sharedWorkspace.frontmostApplication;
  const source = app.isNil() ? null : ObjC.unwrap(app.localizedName);

  if (types.includes("public.file-url")) {
    const url = $.NSURL.URLWithString(pasteboard.stringForType("public.file-url"));
    return { kind: "file", path: ObjC.unwrap(url.path), source };
  }
  const text = ObjC.unwrap(pasteboard.stringForType("public.utf8-plain-text"));
  if (text) return { kind: "text", text, source };

  const type = types.includes("public.png") ? "public.png" : types.includes("public.tiff") ? "public.tiff" : null;
  if (!type) return null;
  const bitmap = $.NSBitmapImageRep.imageRepWithData(pasteboard.dataForType(type));
  if (bitmap.isNil()) return null;
  const png = bitmap.representationUsingTypeProperties(PNG, $({}));
  $.NSFileManager.defaultManager.createDirectoryAtPathWithIntermediateDirectoriesAttributesError(
    images, true, $(), $(),
  );
  const path = `${images}/${Date.now()}.png`;
  if (!png.writeToFileAtomically(path, true)) return null;
  return { kind: "image", path, width: bitmap.pixelsWide, height: bitmap.pixelsHigh, source };
}

function run(argv) {
  const images = argv[0];
  const pasteboard = $.NSPasteboard.generalPasteboard;
  // What's on the pasteboard already was copied before we started.
  let seen = pasteboard.changeCount;
  emit({ kind: "ready" });
  for (;;) {
    delay(0.5);
    const count = pasteboard.changeCount;
    if (count !== seen) {
      seen = count;
      try {
        const copied = read(pasteboard, images);
        if (copied) emit(copied);
      } catch (error) {
        emit({ kind: "error", message: String(error) });
      }
    }
  }
}
